language: php

php:
  - 7.0

before_script:
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction


install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls
  # or enable logging
  - travis_retry php vendor/bin/coveralls -v